### ISSUE TITLE
flutter build aar

### ISSUE THREAD

**Issue by hua407035000** [CarGuo/flutter_app_lib#3]
Could not find method readPropertiesIfExist() for arguments [G:\jkd-flutter\sdfsd\sdfsdfsdf\.flutter-plugins] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

请问这个问题有遇到过吗？

**Comment by CarGuo** [comment]
看起来是gradle版本兼容问题？

**Comment by hua407035000** [comment]
classpath 'com.android.tools.build:gradle:3.2.1'

**Comment by hua407035000** [comment]
gradle version : 4.10.2  请大佬指点一下

**Comment by CarGuo** [comment]
这个项目用的是：

classpath 'com.android.tools.build:gradle:3.2.1'
distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip

我用官方 stable 创建的 plugin 也是：

classpath 'com.android.tools.build:gradle:3.2.1'
distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip

执行 flutter build aar 没问题

<img width="753" alt="image" src="https://user-images.githubusercontent.com/10770362/67263861-ed6efd80-f4db-11e9-9e3e-90ff1b2b54ce.png">
